### PR TITLE
Add reference to akka-persistence-titan plugin

### PR DESCRIPTION
**Pull request by acflorea**
Add reference to akka-persistence-titan plugin

### CODE REVIEW

**Comment by ktoso** [comment]
Interesting, how does it perform / make sense? Titan is a graph database if I remember correctly.

**Comment by acflorea** [comment]
Yes, Titan is a graph database. I've tested the plugin with Titan backed up by Cassandra and Elasticsearch, it performs OK on the project I am working on. Currently I'm using it to generate some interesting statistics (think that each journal / snapshot message can be linked to additional data - this version of the plugin is not yet release ready but it will be published soon. The simplest example would be the actual command but serialised in a human readable format). I was already using Titan add I first started with the plain Cassandra plugin but soon realised the stored data is not really readable from a 3rd party client due to the used serialisation algorithm so I had to chose either to change the Cassandra plugin (and lose Titan's flexibility in choosing the storage layer) or develop a Titan plugin. I chose the 2nd approach :)

**Comment by ktoso** [comment]
Interesting :-)
Thanks for open sourcing the plugin!

**Comment by acflorea** [comment]
Thank you!

**Pull request merged**
