### PR TITLE
small adjustment of 2.4.0 news item

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by patriknw** [comment]
@rkuhn were there other (important) changes that I missed in the conversion?

**Comment by rkuhn** [comment]
just some grammar touch-ups all over the list, I think

**Comment by ktoso** [comment]
LGTM :)

**Comment by patriknw** [comment]
ok, I did a textual diff to see what was changed, but probably I created this markdown before you changed it. I think it's good enough.

**Pull request merged**
