### PR TITLE
improve current version visibility

### PR DESCRIPTION
**Pull request by ktoso**
documentation___akka

### CODE REVIEW

**Comment by chbatey** [comment]
I think this is a good ideal.

Given we only have two versions we could instead put it above the modules section? Will also make it clear that the modules aren't versioned independently apart from HTTP.

**Comment by johanandren** [comment]
I, agree that it is noisy to have it on every Akka core module given that it will always be the same. But shouldn't we then have the version also for Alpakka and commercial (which adds som extra burden when releasing those - is it really worth it)?

**Comment by johanandren** [comment]
But as a newcomer you don't need to know because you just copy-paste the dependency or click the link/use the search box and end up in the right version of the docs?

**Comment by ktoso** [comment]
Yay or Nay please, can I merge this or not?

**Comment by ktoso** [comment]
> But as a newcomer you don't need to know because you just copy-paste the dependency or click the link/use the search box and end up in the right version of the docs?

At least now you'd see which things are on a diff version etc. Now it is very hidden which I believe is not good

**Comment by ktoso** [comment]
Thanks!

**Pull request merged**
