### PR TITLE
Adding guillaumebreton/play-json-support

### PR DESCRIPTION
**Pull request by ktoso**
Hi @guillaumebreton,
I hope you won't mind us adding you to the community page for more exposure! :-)

Thanks a lot for contributing this support library!

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM!

**Comment by guillaumebreton** [comment]
Sure! it works for me :)

**Comment by ktoso** [comment]
Actually, let's wait for you and @hseeberger to figure out which/where this support module will live since you both implemented such projects. If you converge on one let's add that one here then :-)

Thanks!

**Comment by ktoso** [comment]
Closing - we debated the way forward on this some time ago in the akka/akka repo.

**Pull request closed without merging**
