### PR TITLE
Add wget tab to dependencies site

### PR DESCRIPTION
**Pull request by ktoso**
Add wget tab with direct urls to artifacts, by popular demand - as a replacement to the distribution zip file.

### CODE REVIEW

**Comment by patriknw** [comment]
@ktoso Something wrong, nothing shown in the tab: http://akka.io/docs/

**Comment by ktoso** [comment]
Force a refresh :)
Though yes there's one typo - missing newline - fixing now

**Comment by ktoso** [comment]
akka_documentation___akka

**Comment by ktoso** [comment]
All good now: 
akka_documentation___akka

**Comment by patriknw** [comment]
got it, thanks

**Comment by johanandren** [comment]
Man, if you keep adding stuff to the old page how will I ever be able to get the new layout done? ;)

LGTM

**Pull request merged**
