### PR TITLE
Sponsor logos on start page

### PR DESCRIPTION
**Pull request by johanandren**
Desktop and mobile size screen:
Screen Shot 2019-08-19 at 09 33 49
Screen Shot 2019-08-19 at 09 33 40

### CODE REVIEW

**Comment by johanandren** [comment]
Pretty much just mimic:ed the play landing page: https://www.playframework.com

**Comment by patriknw** [comment]
could we have some more space between the two logos in the Desktop screen?

**Comment by johanandren** [comment]
I can do this:
Screen Shot 2019-08-19 at 11 05 44

but then that messes up this:
Screen Shot 2019-08-19 at 11 05 56

**Comment by patriknw** [comment]
FYI @dragos

**Pull request merged**
