### PR TITLE
Clarify that the dist downloads are for java also

### PR DESCRIPTION
**Pull request by patriknw**
Will there be a confusion about java 7 and java 8 being supported?

### CODE REVIEW

**Comment by bantonsson** [comment]
b0rked commit message?

LGTM

**Comment by patriknw** [comment]
thanks, unb0rked

**Comment by drewhk** [comment]
Wait, where is the actual clarification?

**Comment by patriknw** [comment]
I added "and Java 6" to each link title, e.g. "Akka 2.3.9 for Scala 2.10 and Java 6".

**Comment by drewhk** [comment]
buh, long lines and a dummy me. LGTM

**Comment by ktoso** [comment]
Technically `6+` may sound better, LGTM in any case :-)

**Comment by patriknw** [comment]
`6+` yes, I'm fine with that, or will that add another level of confusion?
opinions by anyone else?

**Comment by patriknw** [comment]
changed to 6+

**Pull request merged**
